CREATE TABLE IF NOT EXISTS servicebc.cats_gdx
(
  "ip" VARCHAR(255) ENCODE ZSTD NOT NULL,
  "user" VARCHAR(255) ENCODE ZSTD,
  "group" VARCHAR(255) ENCODE ZSTD,
  "govdate" TIMESTAMPTZ ENCODE ZSTD,
  "get_string" VARCHAR(4095) ENCODE ZSTD NOT NULL,
  "response" BIGINT ENCODE ZSTD NOT NULL,
  "size" BIGINT ENCODE ZSTD,
  "refer" VARCHAR(4095) ENCODE ZSTD,
  "port" BIGINT ENCODE ZSTD NOT NULL,
  "proxy" BIGINT ENCODE ZSTD,
  "gdx_id" BIGINT IDENTITY (0,1) NOT NULL
);

GRANT SELECT ON servicebc.cats_gdx_gdxdsd_2342 TO "looker";
