DROP TABLE IF EXISTS servicebc.office_info;
CREATE TABLE servicebc.office_info
( "id" BIGINT ENCODE ZSTD NOT NULL,
  "start_date" TIMESTAMP ENCODE ZSTD,
  "end_date" TIMESTAMP ENCODE ZSTD,
  "SDB Site" VARCHAR(255) ENCODE ZSTD,
  "Locality" VARCHAR(255) ENCODE ZSTD,
  "PSADEPTID" VARCHAR(255) ENCODE ZSTD,
  "GA" VARCHAR(255) ENCODE ZSTD,
  "GA email" VARCHAR(255) ENCODE ZSTD,
  "FTES" VARCHAR(255) ENCODE ZSTD,
  "OFFICESIZE" VARCHAR(255) ENCODE ZSTD,
  "AREA" VARCHAR(255) ENCODE ZSTD,
  "AREAMANAGER" VARCHAR(255) ENCODE ZSTD,
  "ASM email" VARCHAR(255) ENCODE ZSTD,
  "RMSOFFICECODE" BIGINT ENCODE ZSTD,
  "SNOFFICENAME" VARCHAR(255) ENCODE ZSTD,
  "Address" VARCHAR(255) ENCODE ZSTD,
  "Site_Phone_No" VARCHAR(255) ENCODE ZSTD,
  "Site_Fax_no" VARCHAR(255) ENCODE ZSTD,
  "Website_URL" VARCHAR(255) ENCODE ZSTD,
  "Site_Email" VARCHAR(255) ENCODE ZSTD,
  "Google_Location_ID" VARCHAR(255) ENCODE ZSTD,
  "Latitude" VARCHAR(255) ENCODE ZSTD,
  "Longitude" VARCHAR(255) ENCODE ZSTD,
  "Office Code" BIGINT ENCODE ZSTD,
  "Services - Map" VARCHAR(2047) ENCODE ZSTD,
  "Description" VARCHAR(1023) ENCODE ZSTD,
  "Item Type" VARCHAR(255) ENCODE ZSTD,
  "Path" VARCHAR(255) ENCODE ZSTD,
  "Site" VARCHAR(255) ENCODE ZSTD );

GRANT SELECT ON servicebc.office_info TO "looker";
GRANT SELECT ON servicebc.office_info TO "datamodeling";
